name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ github.token }}
        stale-issue-message: "This issue is stale because it has been open for 60 days with no activity."
        close-issue-message: "This issue was closed because it has been inactive for 60 days since being marked as stale."
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-issue-stale: 60
        days-before-issue-close: 60
